[Feat/54] Matching Found Emit 기능 구현
Gamegoo-repo/Gamegoo-socket-server pull request #55
Opened 2024-08-17 10:10 UTC by rimi3226

## 🚀 개요

## 🔍 변경사항
 - 우선순위 값에 따라 짝 지어주기
 - Matching 코드 리팩토링
 - PriorityTree 메소드 추가 구현

## ⏳ 작업 내용
 - [ ] 매칭 들어왔을 때 priority 값이 서로 55가 넘을 경우 매칭 emit 보내기
 - [ ] 매칭 들어온지 2분 지났을 때 priority 값이 서로 50이 넘을 경우 매칭 emit 보내기
 - [ ] priorityTable 트리 구조로 정렬되도록 구현
 - [ ] 한 유저당 두개 이상의 매칭을 동시에 실행하지 못하도록 제한

### 📝 논의사항

2024-08-17 11:46 UTC, Eunjin3395 requested changes

2024-08-17 11:46 UTC, Eunjin3395 commented on socket/handlers/matching/matchingHandler/matchingStartedHandler.js
> +                });
여기서 socket event emit할 때에는 socket/common/responseFormatter로 이벤트 응답 형식을 통일해주시면 더 좋을 것 같아요!

```suggestion
  socket.emit("my-message-broadcast-success", formatResponse("my-message-broadcast-success", data));
```

이런식으로 이벤트 이름과 같이 보낼 data를 넘겨주면 됩니다!

2024-08-17 11:46 UTC, Eunjin3395 commented on socket/handlers/matching/matchingHandler/matchingStartedHandler.js
> +                });
그리고 matching_found 이벤트는 내 소켓 + 매칭 상대방 소켓에게도 보내주어야 할 것 같아요..!

2024-08-17 11:46 UTC, Eunjin3395 commented on socket/handlers/matching/matchingListeners.js
> +      }, 2 * 60 * 1000); // 2분 = 120,000ms
점수가 55점 이상인 소켓이 있어서 이미 한번 matching_found가 emit된 후, 2분 후에 또 다시 matching_found가 emit되는데 이래도 괜찮은 것인가요?! 아니면 이 부분은 나중에 추가하실 예정이신건지 궁금합니다..!

2024-08-17 11:46 UTC, Eunjin3395 commented on socket/handlers/matching/matchingListeners.js
> +    if (usersInRoom.has(socket.id)) {
주석에는 socket.memberId, 실제 코드에는 socket.id로 되어있는데 어떤게 맞는 것인가요?!

2024-08-17 11:49 UTC, rimi3226 commented on socket/handlers/matching/matchingListeners.js
> +    if (usersInRoom.has(socket.id)) {
앗 socket.id가 맞습니다! 주석 수정하겠습니다

2024-08-17 11:54 UTC, Eunjin3395 commented on socket/handlers/matching/matchingListeners.js
> +      }, 2 * 60 * 1000); // 2분 = 120,000ms
1번 소켓 매칭 요청 -> 2번 소켓 매칭 요청 -> 1,2번 매칭 성공 -> 1번 소켓 disconnect 된 경우 2분 후 이 콜백함수 실행으로 인해서 2번소켓에서 findMatching 메소드 실행하면서 무한 루프를 돌게 됩니다..!
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/19088827-6ff1-4cce-bb03-69d7fc12c768">

2024-08-19 04:42 UTC, Eunjin3395 approved these changes
고생하셨습니다!

2024-08-19 04:52 UTC, merged