[Fix/69] 매칭 관련 수정
Gamegoo-repo/Gamegoo-socket-server pull request #70
Opened 2024-09-04 09:50 UTC by rimi3226

## 🚀 개요
매칭 status 변경할 때 gameMode 변경하는거 추가, client에서 matching-fail 소켓 이벤트 받을 때 matchingSuccessCallback 취소하기
## 🔍 변경사항
- matching API request 에 gameMode 추가
- client에서 matching-fail 시 matchingSuccessCallback callback 취소

## ⏳ 작업 내용
- [ ] matching STATUS 관련 API request 에 gameMode 추가
- [ ]  client에서 matching-fail 시 matchingSuccessCallback callback 취소

### 📝 논의사항

2024-09-04 10:17 UTC, Eunjin3395 requested changes

2024-09-10 04:57 UTC, Eunjin3395 commented on socket/handlers/matching/matchingSocketListeners.js
> +      emitMatchingFail(socket);
매칭 거절하기 버튼을 누른 당사자에게도 matching-fail 이벤트가 가는 것인가요?

2024-09-10 04:58 UTC, Eunjin3395 commented on socket/handlers/matching/matchingSocketListeners.js
> +    const otherSocket = await getSocketIdByMemberId(io, socket.matchingTarget);
여기 otherSocket은 사용하는 일이 없는 것 같습니다!

2024-09-10 05:05 UTC, Eunjin3395 approved these changes
고생하셨습니다 !

2024-09-10 07:17 UTC, rimi3226 commented on socket/handlers/matching/matchingSocketListeners.js
> +      emitMatchingFail(socket);
네네 원래는 버튼 누르는 함수 내에서 콜백 삭제, alert() 진행했습니다.
그런데 프론트 개발자님이 매칭 실패 시 필터링된 게시판에 사용할 사용자 데이터가 필요하다고 하셔서,
matching-fail 시, 사용자 데이터를 보내드리려고 따로따로 emit 했습니다.

2024-09-10 07:17 UTC, rimi3226 commented on socket/handlers/matching/matchingSocketListeners.js
> +    const otherSocket = await getSocketIdByMemberId(io, socket.matchingTarget);
넵! 변경하겠습니다.

2024-09-10 07:21 UTC, merged